# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - mig
    desc: "migrate"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations